import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Appbar from "@/components/Appbar";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pixaura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-bg-gradient ${poppins.variable} font-poppins`}>
        <Appbar />
        {children}
      </body>
    </html>
  );
}
